In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [56]:
df = pd.read_csv('glassdoor_cleaned2.csv')

In [57]:
df.columns

Index(['Company', 'Job_Ratings', 'Job_Title', 'Application_Link',
       'Job_Tracking', 'Offer_age', 'City', 'State', 'Hourly', 'Min_Pay',
       'Max_Pay', 'Average_Pay'],
      dtype='object')

In [58]:
df_model = df[["Company" , "Job_Ratings" , "Job_Title", "Offer_age", "State", "Min_Pay", "Max_Pay", "Average_Pay" ]]

In [59]:
df_dum = pd.get_dummies(df_model)

In [60]:
df_dum

,Job_Ratings,Offer_age,Min_Pay,Max_Pay,Average_Pay,Company_3M,Company_AGTEGRA COOPERATIVE,"Company_AKRF, Inc.",Company_ASML,Company_AbbVie,...,"State_ Pierce, WA",State_ SC,State_ SD,"State_ St. Louis, MO",State_ TN,State_ TX,State_ UT,State_ VA,State_ WA,State_ WI
0,4.1,30,125.0,125.0,125.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,4.2,3,66.0,100.0,83.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,4.1,16,36.0,52.0,44.0,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,4.0,30,55.0,55.0,55.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,3.8,30,100.0,100.0,100.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,3.4,19,27.0,27.0,27.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
410,3.4,18,27.0,27.0,27.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
411,3.8,4,30.0,30.0,30.0,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
412,4.3,28,45.0,52.0,48.5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
413,4.1,30,75.0,140.0,107.5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [61]:
X = df_dum.drop(['Min_Pay', 'Max_Pay', 'Average_Pay'], axis=1)
y = df_dum[['Min_Pay', 'Max_Pay', 'Average_Pay']]

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [63]:
X_train

,Job_Ratings,Offer_age,Company_3M,Company_AGTEGRA COOPERATIVE,"Company_AKRF, Inc.",Company_ASML,Company_AbbVie,Company_Adobe,Company_Ag Plus,"Company_AgReliant Genetics, LLC",...,"State_ Pierce, WA",State_ SC,State_ SD,"State_ St. Louis, MO",State_ TN,State_ TX,State_ UT,State_ VA,State_ WA,State_ WI
192,4.8,30,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
234,3.5,30,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,4.0,7,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
45,3.6,3,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
245,4.0,15,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,3.9,30,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
106,3.3,10,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
270,4.1,30,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
348,3.7,24,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
102,4.0,30,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [65]:
y_train

     Min_Pay  Max_Pay  Average_Pay
192      NaN      NaN          NaN
234    40.00    58.00        49.00
5      50.00    70.00        60.00
45     45.08    45.08        45.08
245   115.00   168.00       141.50
..       ...      ...          ...
71     53.00    82.00        67.50
106    41.00    60.00        50.50
270    70.00   107.00        88.50
348    40.00    40.00        40.00
102    61.00    76.00        68.50

[331 rows x 3 columns]